### PR TITLE
Update for BPS base patching

### LINKED ISSUE #11: Broken for v31.0.5
I'm sure you already know this, but it's broken as of the latest release for alttpr.

It looks like you need a BPS patcher and some updates to fetch the new base BPS and apply it as well as how to get the randomizer BPS and apply that.

### PR DESCRIPTION
**Pull request by mgius**
Fixes #11.  **This patch is against tag 4.8.3, which looked like the most recent tag/branch prior to removing all the patching code that broke**

Add python-bps as dependency.

Add binary get to http module.

Add apply_bps to apply module.

Reorder create_patched_game so that bps patching occurs first.  BPS
patching checks length of input and output files, so expanding romsize
at this point is not advisable.

### CODE REVIEW

**Comment by mgius** [comment]
I only tested against the LTTP Randomizer endpoint, not against multiworld or customizer or anything like that, although I can't imagine it being too much different.

**Comment by mgius** [comment]
Actually, scratch that, the generated ROMs don't seem to be playable

**Comment by mgius** [comment]
Re-opened, needed to re-wind the target byte stream after handing it off to python-bps.

Was able to use create_patched_game to create a randomized game with my config.

**Comment by tcprescott** [comment]
Thanks for the PR!  I'll take a look at this later.

**Pull request merged**
